version: '2'

services:
  mariadb:
    image: 'bitnami/mariadb:latest'
    volumes:
      - 'mariadb_data:/bitnami/mariadb'
    environment:
      - MARIADB_ROOT_PASSWORD=

  application:
    image: 'bitnami/wordpress:latest'
    ports:
      - '80'
      - '443'
    volumes:
      - 'wordpress_data:/bitnami/wordpress'
      - 'apache_data:/bitnami/apache'
      - 'php_data:/opt/bitnami/php/lib'
    environment:
      - VIRTUAL_HOST=
      - WORDPRESS_USERNAME=Administrator
      - WORDPRESS_PASSWORD=
      - WORDPRESS_EMAIL=
      - WORDPRESS_BLOG_NAME=
      - MARIADB_USER=
      - MARIADB_PASSWORD=

    depends_on:
      - mariadb
volumes:
  mariadb_data:
    driver: local
  wordpress_data:
    driver: local
  apache_data:
    driver: local
  php_data:
    driver: local

networks:
  default:
    external:
      name: nginx-proxy
